/** An RGB color with channels in the inclusive `0`-`255` range. */
export interface RgbColor {
  /** Red channel. */
  readonly r: number;
  /** Green channel. */
  readonly g: number;
  /** Blue channel. */
  readonly b: number;
}

/** An RGB color with an alpha channel between `0` and `1`. */
export interface RgbaColor extends RgbColor {
  /** Opacity from fully transparent (`0`) to fully opaque (`1`). */
  readonly a: number;
}

/** A portable CSS color string or structured RGB(A) value. */
export type TerminalColor = string | RgbColor | RgbaColor;

/** A normalized color used in render snapshots. */
export interface RenderColor extends RgbColor {
  /** Opacity. Omitted values are fully opaque. */
  readonly a?: number;
}

/** The color encoding authored by terminal output before theme palette resolution. */
export type CellColor =
  | {
      /** Use the terminal theme's default color. */
      readonly mode: 'default';
    }
  | {
      /** Resolve an indexed ANSI palette entry. */
      readonly mode: 'palette';
      /** Zero-based ANSI palette index. */
      readonly value: number;
    }
  | {
      /** Use an explicit RGB color. */
      readonly mode: 'rgb';
      /** Explicit color channels authored by terminal output. */
      readonly value: RgbColor;
    };

/** Light or dark visual appearance advertised to terminal applications. */
export type ThemeAppearance = 'dark' | 'light';

/** Colors used to render the terminal and its ANSI palette. */
export interface TerminalTheme {
  /** Theme appearance. Derived from the background when omitted. */
  readonly appearance?: ThemeAppearance;
  /** Default text color. */
  readonly foreground?: TerminalColor;
  /** Default cell background color. */
  readonly background?: TerminalColor;
  /** Cursor color. */
  readonly cursor?: TerminalColor;
  /** Text color drawn underneath a block cursor. */
  readonly cursorAccent?: TerminalColor;
  /** Active selection background. */
  readonly selectionBackground?: TerminalColor;
  /** Optional active selection foreground. */
  readonly selectionForeground?: TerminalColor;
  /** Inactive selection background. */
  readonly selectionInactiveBackground?: TerminalColor;
  /** ANSI color 0. */
  readonly black?: TerminalColor;
  /** ANSI color 1. */
  readonly red?: TerminalColor;
  /** ANSI color 2. */
  readonly green?: TerminalColor;
  /** ANSI color 3. */
  readonly yellow?: TerminalColor;
  /** ANSI color 4. */
  readonly blue?: TerminalColor;
  /** ANSI color 5. */
  readonly magenta?: TerminalColor;
  /** ANSI color 6. */
  readonly cyan?: TerminalColor;
  /** ANSI color 7. */
  readonly white?: TerminalColor;
  /** ANSI color 8. */
  readonly brightBlack?: TerminalColor;
  /** ANSI color 9. */
  readonly brightRed?: TerminalColor;
  /** ANSI color 10. */
  readonly brightGreen?: TerminalColor;
  /** ANSI color 11. */
  readonly brightYellow?: TerminalColor;
  /** ANSI color 12. */
  readonly brightBlue?: TerminalColor;
  /** ANSI color 13. */
  readonly brightMagenta?: TerminalColor;
  /** ANSI color 14. */
  readonly brightCyan?: TerminalColor;
  /** ANSI color 15. */
  readonly brightWhite?: TerminalColor;
  /** ANSI colors 16 through 255. Missing entries are generated by Ghostty. */
  readonly extendedAnsi?: readonly TerminalColor[];
  /**
   * Positional ANSI palette entries starting at index 0.
   *
   * @deprecated Prefer named ANSI properties and {@link TerminalTheme.extendedAnsi}.
   */
  readonly palette?: readonly TerminalColor[];
}

/** Fully normalized terminal theme. */
export interface ResolvedTerminalTheme {
  /** Resolved light or dark appearance. */
  readonly appearance: ThemeAppearance;
  /** Default text color. */
  readonly foreground: RgbaColor;
  /** Default background color. */
  readonly background: RgbaColor;
  /** Cursor color. */
  readonly cursor: RgbaColor;
  /** Text color underneath a block cursor. */
  readonly cursorAccent: RgbaColor;
  /** Active selection background. */
  readonly selectionBackground: RgbaColor;
  /** Active selection foreground, or `null` to retain the cell foreground. */
  readonly selectionForeground: RgbaColor | null;
  /** Inactive selection background. */
  readonly selectionInactiveBackground: RgbaColor;
  /** Complete 256-color ANSI palette. */
  readonly palette: readonly RgbaColor[];
}

/** Character-grid and backing-surface dimensions for a terminal. */
export interface TerminalGeometry {
  /** Number of character columns. */
  readonly cols: number;
  /** Number of character rows. */
  readonly rows: number;
  /** Cell width in device pixels. */
  readonly cellWidthPx: number;
  /** Cell height in device pixels. */
  readonly cellHeightPx: number;
  /** Total backing-surface width in device pixels. */
  readonly widthPx: number;
  /** Total backing-surface height in device pixels. */
  readonly heightPx: number;
}

/**
 * Initial options shared by headless and browser terminals.
 *
 * @remarks
 * Browser terminals measure cell dimensions from their font and device pixel ratio. The explicit
 * cell dimensions are primarily useful for the headless runtime.
 */
export interface CoreTerminalOptions {
  /** @defaultValue `80` */
  readonly cols?: number;
  /** @defaultValue `24` */
  readonly rows?: number;
  /** @defaultValue `9` in the headless runtime. */
  readonly cellWidthPx?: number;
  /** @defaultValue `18` in the headless runtime. */
  readonly cellHeightPx?: number;
  /** @defaultValue `10000` */
  readonly scrollbackLines?: number;
  /** Default cursor shape used until an application changes it. @defaultValue `'block'` */
  readonly defaultCursorStyle?: CursorStyle;
  /** Whether the default cursor blinks. @defaultValue `false` */
  readonly defaultCursorBlink?: boolean;
  /** @defaultValue {@link DEFAULT_THEME} */
  readonly theme?: TerminalTheme;
}

/** A URL, bytes, response, or compiled module accepted as a WebAssembly source. */
export type WasmSource = URL | string | ArrayBuffer | Uint8Array | WebAssembly.Module | Response;

/** WebAssembly sources used to initialize a headless Ghostty runtime. */
export interface CoreRuntimeOptions {
  /** @defaultValue {@link DEFAULT_WASM_URL} */
  readonly wasm?: WasmSource;
  /** @defaultValue {@link DEFAULT_CALLBACKS_URL} */
  readonly callbacksWasm?: WasmSource;
}

/** Lifecycle phase for a key input event. */
export type KeyAction = 'press' | 'repeat' | 'release';

/** Bit flags accepted by key and pointer input APIs. */
export const KeyModifiers = {
  /** Shift modifier bit. */
  shift: 1 << 0,
  /** Control modifier bit. */
  control: 1 << 1,
  /** Alt/Option modifier bit. */
  alt: 1 << 2,
  /** Meta/Command modifier bit. */
  meta: 1 << 3,
  /** Caps Lock modifier bit. */
  capsLock: 1 << 4,
  /** Num Lock modifier bit. */
  numLock: 1 << 5,
} as const;

/** A physical or composed keyboard input sent to Ghostty. */
export interface KeyInput {
  /** A KeyboardEvent.code value such as `KeyA`, `ArrowUp`, or `Enter`. */
  readonly code: string;
  /** Key lifecycle phase. Defaults to `press`. */
  readonly action?: KeyAction;
  /** Active {@link KeyModifiers} bit mask. */
  readonly modifiers?: number;
  /** Modifier bits already consumed by text generation. */
  readonly consumedModifiers?: number;
  /** Whether an input-method composition is active. */
  readonly composing?: boolean;
  /** Composed text associated with the key. */
  readonly text?: string;
  /** Unicode code point before keyboard-layout shifting. */
  readonly unshiftedCodepoint?: number;
}

/** Pointer-button lifecycle phase. */
export type MouseAction = 'press' | 'release' | 'motion';
/** Mouse button names understood by Ghostty. */
export type MouseButton =
  | 'left'
  | 'right'
  | 'middle'
  | 'four'
  | 'five'
  | 'six'
  | 'seven'
  | 'eight'
  | 'nine'
  | 'ten'
  | 'eleven';

/** A pointer input in terminal backing-surface coordinates. */
export interface PointerInput {
  /** Pointer action to perform. */
  readonly action: MouseAction;
  /** Button involved in a press or release. */
  readonly button?: MouseButton;
  /** Horizontal position in device pixels. */
  readonly x: number;
  /** Vertical position in device pixels. */
  readonly y: number;
  /** Active {@link KeyModifiers} bit mask. */
  readonly modifiers?: number;
  /** Whether any pointer button remains pressed during motion. */
  readonly anyButtonPressed?: boolean;
  /** Hold Shift in a browser UI to select text even when an application tracks the mouse. */
  readonly forceSelection?: boolean;
  /** Use rectangular rather than linear text selection. */
  readonly rectangle?: boolean;
  /** Event timestamp in milliseconds. */
  readonly timeMs?: number;
}

/** Result of encoding a pointer action. */
export interface PointerResult {
  /** Bytes to forward to the PTY, possibly empty. */
  readonly data: Uint8Array;
  /** Whether Ghostty updated its text selection. */
  readonly selected: boolean;
}

/** Formatting options for selected terminal text. */
export interface SelectionFormatOptions {
  /** Output encoding for the selection. */
  readonly format?: 'plain' | 'vt' | 'html';
  /** Join wrapped physical rows into logical lines. */
  readonly unwrap?: boolean;
  /** Remove trailing whitespace. */
  readonly trim?: boolean;
}

/** OSC progress-report state. */
export type ProgressState = 'remove' | 'set' | 'error' | 'indeterminate' | 'pause';

/** Amount of terminal content invalidated by the latest parse. */
export type DirtyState = 'clean' | 'partial' | 'full';
/** Cursor shape requested by the terminal application. */
export type CursorStyle = 'bar' | 'block' | 'underline' | 'block-hollow';
/** Display-width role of a rendered cell. */
export type CellWidth = 'narrow' | 'wide' | 'spacer-tail' | 'spacer-head';
/** Semantic role reported for terminal content. */
export type SemanticContent = 'output' | 'input' | 'prompt' | 'unknown';

/** Text attributes attached to a rendered cell. */
export interface CellStyle {
  /** Bold text flag. */
  readonly bold: boolean;
  /** Italic text flag. */
  readonly italic: boolean;
  /** Faint/dim text flag. */
  readonly faint: boolean;
  /** Blinking text flag. */
  readonly blink: boolean;
  /** Foreground/background inversion flag. */
  readonly inverse: boolean;
  /** Hidden text flag. */
  readonly invisible: boolean;
  /** Strikethrough flag. */
  readonly strikethrough: boolean;
  /** Overline flag. */
  readonly overline: boolean;
  /** Ghostty underline style value. */
  readonly underline: number;
}

/** One visible terminal cell. */
export interface RenderCell {
  /** Zero-based column. */
  readonly x: number;
  /** Grapheme rendered in the cell. */
  readonly text: string;
  /** Cell-width role. */
  readonly width: CellWidth;
  /** Text attributes. */
  readonly style: CellStyle;
  /** Resolved foreground, or `null` to use the frame default. */
  readonly foreground: RenderColor | null;
  /** Resolved background, or `null` to use the frame default. */
  readonly background: RenderColor | null;
  /** Original foreground encoding, when the backing API exposes it. */
  readonly foregroundSource?: CellColor;
  /** Original background encoding, when the backing API exposes it. */
  readonly backgroundSource?: CellColor;
  /** Original underline-color encoding, when the backing API exposes it. */
  readonly underlineSource?: CellColor;
  /** Whether the cell belongs to a hyperlink. */
  readonly hyperlink: boolean;
  /** OSC 8 URI associated with the cell, or `null` when it is not a hyperlink. */
  readonly hyperlinkUri?: string | null;
  /** Semantic content role. */
  readonly semanticContent: SemanticContent;
}

/** Selected columns on a rendered row. */
export interface RenderSelection {
  /** Inclusive zero-based start column. */
  readonly start: number;
  /** Exclusive zero-based end column. */
  readonly end: number;
}

/** One rendered row and its cell-level details. */
export interface RenderRow {
  /** Zero-based row in the current viewport. */
  readonly y: number;
  /** Row text with visual gaps preserved and unused trailing columns omitted. */
  readonly text: string;
  /** Renderable cells in column order. */
  readonly cells: readonly RenderCell[];
  /** Whether this row wraps into the following row. */
  readonly wrapped: boolean;
  /** Whether this row continues a preceding wrapped row. */
  readonly wrapContinuation: boolean;
  /** Selected column range, if any. */
  readonly selection: RenderSelection | null;
}

/** Cursor state for a render frame. */
export interface RenderCursor {
  /** Zero-based cursor column, or `null` when absent. */
  readonly x: number | null;
  /** Zero-based cursor row, or `null` when absent. */
  readonly y: number | null;
  /** Whether the cursor should be drawn. */
  readonly visible: boolean;
  /** Whether the cursor should blink. */
  readonly blinking: boolean;
  /** Whether the cursor is in a password-input field. */
  readonly passwordInput: boolean;
  /** Whether the cursor occupies the tail of a wide grapheme. */
  readonly wideTail: boolean;
  /** Requested cursor shape. */
  readonly style: CursorStyle;
}

/** Resolved colors for a render frame. */
export interface RenderColors {
  /** Default text color. */
  readonly foreground: RenderColor;
  /** Default background color. */
  readonly background: RenderColor;
  /** Cursor color, or `null` for the default. */
  readonly cursor: RenderColor | null;
  /** Text color underneath a block cursor. */
  readonly cursorAccent?: RenderColor;
  /** Active selection background. */
  readonly selectionBackground?: RenderColor;
  /** Active selection foreground, or `null` to preserve the cell foreground. */
  readonly selectionForeground?: RenderColor | null;
  /** Inactive selection background. */
  readonly selectionInactiveBackground?: RenderColor;
  /** Resolved 256-color palette. */
  readonly palette: readonly RenderColor[];
}

/** Incremental frame produced after parsing or invalidation. */
export interface RenderFrame {
  /** Number of columns. */
  readonly cols: number;
  /** Number of rows. */
  readonly rows: number;
  /** Frame invalidation level. */
  readonly dirty: DirtyState;
  /** Rows changed since the previous render. */
  readonly changedRows: readonly RenderRow[];
  /** Cursor state. */
  readonly cursor: RenderCursor;
  /** Resolved frame colors. */
  readonly colors: RenderColors;
}

/** Complete snapshot of the visible viewport. */
export interface ViewportSnapshot extends Omit<RenderFrame, 'changedRows'> {
  /** Every visible row in viewport order. */
  readonly viewportRows: readonly RenderRow[];
}

/** Half-open absolute row range within the active terminal buffer. */
export interface TerminalBufferRange {
  /** First row to read, measured from the oldest retained row. */
  readonly start: number;
  /** Row after the last row to read. */
  readonly end: number;
}

/** Active screen and scroll position metadata for terminal buffer consumers. */
export interface TerminalBufferState {
  /** Currently active primary or alternate screen. */
  readonly screen: 'normal' | 'alternate';
  /** Number of retained rows, including the visible viewport. */
  readonly totalRows: number;
  /** Number of retained rows above the bottom viewport. */
  readonly scrollbackRows: number;
  /** Absolute zero-based offset of the first visible row. */
  readonly viewportY: number;
  /** Number of rows in the visible viewport. */
  readonly viewportLength: number;
  /** Cursor column on the active screen. */
  readonly cursorX: number;
  /** Cursor row on the active screen. */
  readonly cursorY: number;
  /** Authoritative terminal modes at this revision. */
  readonly modes?: TerminalModeState;
  /** Current SGR attributes used for subsequently written cells. */
  readonly cursorAttributes?: TerminalCursorAttributes;
  /** Monotonic revision for buffer-affecting operations. */
  readonly revision: number;
}

/** Stable terminal mode state queried directly from Ghostty. */
export interface TerminalModeState {
  /** Whether cursor keys emit application-mode sequences. */
  readonly applicationCursorKeysMode: boolean;
  /** Whether the numeric keypad emits application-mode sequences. */
  readonly applicationKeypadMode: boolean;
  /** Whether pasted input must be wrapped in bracketed-paste delimiters. */
  readonly bracketedPasteMode: boolean;
  /** Whether newly written cells insert instead of replacing existing cells. */
  readonly insertMode: boolean;
  /** Active mouse-reporting protocol. */
  readonly mouseTrackingMode: 'none' | 'x10' | 'vt200' | 'drag' | 'any';
  /** Whether cursor addressing is relative to the scrolling region. */
  readonly originMode: boolean;
  /** Whether reverse wrapping at the left margin is enabled. */
  readonly reverseWraparoundMode: boolean;
  /** Whether focus changes are reported to the terminal application. */
  readonly sendFocusMode: boolean;
  /** Whether synchronized-output mode is active. */
  readonly synchronizedOutputMode: boolean;
  /** Whether output wraps at the right margin. */
  readonly wraparoundMode: boolean;
}

/** Current pen attributes used when the parser writes the next cell. */
export interface TerminalCursorAttributes {
  /** Text styling flags for subsequently written cells. */
  readonly style: CellStyle;
  /** Foreground color encoding for subsequently written cells. */
  readonly foreground: CellColor;
  /** Background color encoding for subsequently written cells. */
  readonly background: CellColor;
  /** Underline color encoding for subsequently written cells. */
  readonly underline: CellColor;
}

/** A row returned by the paged terminal buffer API. */
export interface TerminalBufferRow {
  /** Absolute row index measured from the oldest retained row. */
  readonly index: number;
  /** Stable identity for this retained Ghostty row. */
  readonly id: string;
  /** Concatenated row text. */
  readonly text: string;
  /** Cells in terminal-column order. */
  readonly cells: readonly RenderCell[];
  /** Whether this row wraps into the next row. */
  readonly wrapped: boolean;
  /** Whether this row continues a previous wrapped row. */
  readonly wrapContinuation: boolean;
  /** Selected columns when available. */
  readonly selection: RenderSelection | null;
}

/** Buffer metadata and a requested page of rows captured together. */
export interface TerminalBufferSnapshot {
  /** State corresponding to the returned rows. */
  readonly state: TerminalBufferState;
  /** Requested, clamped rows. */
  readonly rows: readonly TerminalBufferRow[];
}

/** Painted viewport notification carrying the authoritative buffer state. */
export interface TerminalViewportChangeEvent {
  /** Monotonic buffer revision represented by the painted frame. */
  readonly revision: number;
  /** Active buffer and viewport coordinates represented by the frame. */
  readonly state: TerminalBufferState;
}

/** Origin of bytes emitted toward a PTY. */
export type InputSource = 'key' | 'text' | 'paste' | 'mouse' | 'focus' | 'reply';

/** Bytes and origin emitted by a terminal input operation. */
export interface TerminalInputEvent {
  /** Bytes to forward unchanged to the PTY. */
  readonly data: Uint8Array;
  /** Operation that produced the bytes. */
  readonly source: InputSource;
}

/** One MIME-typed clipboard payload. */
export interface ClipboardContent {
  /** MIME type such as `text/plain`. */
  readonly mime: string;
  /** Raw clipboard bytes. */
  readonly data: Uint8Array;
}

/** Clipboard destination used by OSC 52 and the Kitty clipboard protocol. */
export type ClipboardLocation = 'standard' | 'selection' | 'primary';

/** Resource limits for an enabled Kitty clipboard protocol integration. */
export interface ClipboardProtocolOptions {
  /** Maximum bytes retained or accepted for one clipboard transaction. @defaultValue `33554432` */
  readonly maxBytes?: number;
  /** Maximum lifetime of a user-initiated clipboard snapshot. @defaultValue `30000` */
  readonly snapshotTtlMs?: number;
}

/** MIME representations supplied for a user-initiated clipboard paste. */
export interface ClipboardPasteRequest {
  /** Representations of the same logical clipboard value, in preferred order. */
  readonly contents: readonly ClipboardContent[];
  /** Clipboard that supplied the value. @defaultValue `'standard'` */
  readonly location?: ClipboardLocation;
  /** Allows text that can execute commands when bracketed paste is unavailable. @defaultValue `false` */
  readonly allowUnsafe?: boolean;
}

/** Result of applying a MIME-aware clipboard paste to the current terminal state. */
export type ClipboardPasteResult =
  | {
      /** The paste emitted bytes toward the PTY. */
      readonly status: 'written';
      /** Whether Ghostty emitted a Kitty event or used the text fallback. */
      readonly kind: 'kitty' | 'text';
    }
  | {
      /** No compatible content existed, or safety policy rejected fallback text. */
      readonly status: 'empty' | 'unsafe';
    };

/** Clipboard write requested by terminal output. */
export interface ClipboardWriteRequest {
  /** Clipboard target requested by the application. */
  readonly location: ClipboardLocation;
  /** Available MIME representations. */
  readonly contents: readonly ClipboardContent[];
  /** Human-readable name supplied by the requesting terminal application. */
  readonly name: string;
  /** Whether Ghostty has an existing session grant for this request. */
  readonly granted: boolean;
  /** Whether the requesting application supplied a grant that could be remembered. */
  readonly canRemember: boolean;
}

/** Desktop notification requested by terminal output. */
export interface TerminalNotification {
  /** Notification title. */
  readonly title: string;
  /** Notification body. */
  readonly body: string;
}

/** Progress state and optional percentage reported by terminal output. */
export interface TerminalProgressReport {
  /** Progress lifecycle state. */
  readonly state: ProgressState;
  /** Percentage from `0` to `100`, or `null` when indeterminate. */
  readonly progress: number | null;
}

/** Event payloads emitted by the headless terminal core. */
export interface TerminalEventMap {
  /** Bytes to send to the PTY. */
  readonly input: TerminalInputEvent;
  /** Bell notification. */
  readonly bell: undefined;
  /** Current terminal title. */
  readonly title: string;
  /** Current working directory reported by the shell. */
  readonly cwd: string;
  /** Desktop notification request. */
  readonly notification: TerminalNotification;
  /** Progress report. */
  readonly progress: TerminalProgressReport;
  /** Clipboard write request. */
  readonly clipboardWrite: ClipboardWriteRequest;
  /** Incremental render frame. */
  readonly render: RenderFrame;
  /** Asynchronous terminal failure. */
  readonly error: Error;
}

/** A resource that can be released deterministically. */
export interface Disposable {
  /** Releases the resource. Safe implementations should be idempotent. */
  dispose(): void;
}

/** Target ABI recorded alongside a vendored Ghostty build. */
export interface GhosttyAbiMetadata {
  /** Compilation target, expected to be `wasm32`. */
  readonly target: string;
  /** Pointer size in bytes. */
  readonly pointer_size: number;
  /** `usize` size in bytes. */
  readonly usize_size: number;
  /** Byte order, expected to be `little`. */
  readonly endian: string;
}

/** Reproducibility and ABI metadata for the vendored Ghostty WASM. */
export interface GhosttyBuildMetadata {
  /** Canonical nightly download URL. */
  readonly source: string;
  /** Final URL after redirects. */
  readonly resolvedUrl: string;
  /** ISO-8601 fetch timestamp. */
  readonly fetchedAt: string;
  /** SHA-256 digest of the WASM bytes. */
  readonly sha256: string;
  /** WASM byte length. */
  readonly size: number;
  /** Version reported by Ghostty. */
  readonly ghosttyVersion: string;
  /** Source commit reported by Ghostty, when available. */
  readonly ghosttyCommit: string | null;
  /** Ghostty ABI manifest schema version. */
  readonly abiSchema: number;
  /** Target ABI details. */
  readonly abi: GhosttyAbiMetadata;
}
