(module
  (type $terminal_event (func (param i32 i32)))
  (type $terminal_pointer_event (func (param i32 i32 i32)))
  (type $terminal_write (func (param i32 i32 i32 i32)))
  (type $terminal_result_event (func (param i32 i32 i32) (result i32)))
  (type $secure_random (func (param i32 i32 i32) (result i32)))
  (type $mime_reader (func (param i32 i32 i32) (result i32)))

  (import "host" "write_pty" (func $write_pty (type $terminal_write)))
  (import "host" "bell" (func $bell (type $terminal_event)))
  (import "host" "title_changed" (func $title_changed (type $terminal_event)))
  (import "host" "pwd_changed" (func $pwd_changed (type $terminal_event)))
  (import "host" "desktop_notification" (func $desktop_notification (type $terminal_pointer_event)))
  (import "host" "progress_report" (func $progress_report (type $terminal_pointer_event)))
  (import "host" "clipboard_read" (func $clipboard_read (type $terminal_pointer_event)))
  (import "host" "clipboard_write" (func $clipboard_write (type $terminal_pointer_event)))
  (import "host" "mime_reader" (func $mime_reader (type $mime_reader)))
  (import "host" "random_secure" (func $random_secure (type $secure_random)))
  (import "host" "color_scheme" (func $color_scheme (type $terminal_result_event)))

  (export "write_pty" (func $write_pty))
  (export "bell" (func $bell))
  (export "title_changed" (func $title_changed))
  (export "pwd_changed" (func $pwd_changed))
  (export "desktop_notification" (func $desktop_notification))
  (export "progress_report" (func $progress_report))
  (export "clipboard_read" (func $clipboard_read))
  (export "clipboard_write" (func $clipboard_write))
  (export "mime_reader" (func $mime_reader))
  (export "random_secure" (func $random_secure))
  (export "color_scheme" (func $color_scheme))
)
